Repository AdityaDwiNugroho/hacktoberfest-stories, pull requests merged in 2025-10, with the labels that each got.

#2 Update stories.json - Lightningxyz
  public/data/stories.json
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest

#4 Fix: Improve responsiveness and layout adjustments in styles.css
  public/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2025, hacktoberfest, opensource-contribution

#6 Add: HiddenKeyDev's first Hacktoberfest contribution story
  public/data/stories.json
Labels: hacktoberfest-accepted
